name: snapy
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6.1
  - matplotlib==3.3.2
  - numpy==1.18.5
  - pip==19.3
  - scipy==1.2.0
  - pip:
      - pyquaternion
      - typer==0.3.2
      - -e .[dev]
